config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  root 'home#index'

  get 'home/recorder'
  get 'home/index'
  get 'home/show/:id' => 'home#show'
  get 'home/like'
  get 'home/nokogiri'
  get 'home/delete/:id' => 'home#delete'
  get 'home/correct/:id' => 'home#correct', as: :home_correct
  get 'home/correct_comment/:id' => 'home#correct_comment', as: :home_correct_comment
  get 'home/delete_comment/:id' => 'home#delete_comment', as: :home_delete_comment
  
  post 'home/post'
  post 'home/comment'
  post 'home/correct_process/:id' => 'home#correct_process'
  post 'home/rating/:id' => 'home#rating'
  post 'home/correct_comment_process/:id' => 'home#correct_comment_process', as: :home_correct_comment_process
  post 'star/rating/:id' => 'star#rating', as: :star_rating
  post 'home/upload_tmp'

end

app/models/comment.rb
class Comment < ActiveRecord::Base
    belongs_to  :post        # Post-Comment 1:N
    
    def self.default_scope
      where published: true
    end
end

app/models/difficulty.rb
class Difficulty < ActiveRecord::Base
    belongs_to :person, class_name: :User, foreign_key: :user_id
    belongs_to :message, class_name: :Post, foreign_key: :post_id
end

app/models/like.rb
class Like < ActiveRecord::Base
    belongs_to :story, class_name: :Post, foreign_key: :post_id
    belongs_to :member, class_name: :User, foreign_key: :user_id           # User-Like-Post
end

app/models/post.rb
class Post < ActiveRecord::Base
    belongs_to :user        # User-Post 1:N
    
    has_many :comments      # Post-Comment 1:N
    
    has_many :likes
    has_many :members, through: :likes, class_name: :User               # User-Like-Post M:N
    
    has_many :difficulties
    has_many :persons, through: :difficulties, class_name: :User        # User-Difficult-Post M:N

    def self.default_scope
      where published: true
    end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
         
  has_many :posts       # User-Post 1:N
  
  has_many :likes
  has_many :stories, through: :likes, class_name: :POST     # User-Like-Post M:N
  
  has_many :difficulties
  has_many :messages, through: :difficulties, class_name: :POST     # User-Diffculty-Post M:N
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  # protect_from_forgery with: :exception
end

app/controllers/home_controller.rb
require 'nokogiri'
require 'open-uri'
require 'fileutils'

class HomeController < ApplicationController
  before_action :authenticate_user!
  
  def index
    @posts = Post.all.reverse
  end

  def post
    post_genre = params[:genre]
    post_content = params[:content]
    post_file = params[:file]
    
    uploader = UploadUploader.new
    uploader.store!(post_file)
    
    new_post = Post.new(genre: post_genre, content: post_content, file_name: uploader.url, user_id: current_user.id )
    new_post.save

    redirect_to :back
  end
  
  def like
    like_user = current_user.id
    post_id = params[:post_id]

    isnil = Like.where(user_id: current_user.id, post_id: post_id)

    if isnil.empty?
      likeit = Like.new(user_id: like_user, post_id: post_id)
      likeit.save
    else
      isnil.take.destroy
    end

    @count = Post.find(post_id).members.count
    @post_id = post_id
  end

  def recorder
  end

  def show        # 각각의 POST 상세 보기
    if user_signed_in?
      post_id = params[:id]
      @show = Post.where(id: post_id)
      @count = @show.take.members.count
    else
      redirect_to "/users/sign_in"
    end
  end
  
  def delete
    postid = params[:id]
    userid = current_user.id
    writerid = Post.find(postid).user.id
    
    if userid == writerid
      delete_post = Post.find(postid)
      delete_post.published = false
      delete_post.save
    end
    
    redirect_to "/"
  end
  
  def correct
    postid = params[:id].to_i
    userid = current_user.id
    writerid = Post.find(postid).user.id
    
    @show = Post.where(id: postid)
    @count = @show.take.members.count
  end
  
  def correct_process
    postid = params[:id].to_i
    content = params[:content]
    correct_post = Post.find(postid)
    correct_post.content = content
    correct_post.save
    
    redirect_to "/home/show/#{postid}"
  end

  def comment     # Comment 기능 구현
    title = params[:title]
    singer = params[:singer]
    content = params[:content]
    postid = params[:postid].to_i

    reply = Comment.new(title: title, singer: singer, content: content, post_id: postid, writer: current_user.email)
    reply.save

    # Ajax로 넘기기 위한 변수
    @show_one = Post.where(id: postid).take
  end
  
  def correct_comment
    @c_id = params[:id].to_i
    @c_title = Comment.find(@c_id).title
    @c_singer = Comment.find(@c_id).singer
    @c_content = Comment.find(@c_id).content
  end
  
  def correct_comment_process
    @c_id = params[:id].to_i
    @c_title = params[:title]
    @c_singer = params[:singer]
    @c_content = params[:content]
    
    correct_comment = Comment.find(@c_id)
    correct_comment.title = @c_title
    correct_comment.singer = @c_singer
    correct_comment.content = @c_content
    correct_comment.save
    
    @c_date = Comment.find(@c_id).updated_at
  end
  
  def delete_comment
    @c_id = params[:id].to_i
    
    d_comment = Comment.find(@c_id)
    d_comment.published = false
    d_comment.save
    
    postid = d_comment.post.id
    @show_one = Post.where(id: postid).take
    
    render template: 'home/comment'
  end

  def nokogiri
    songid = params[:song_id].to_i
    @title = Comment.find(songid).title
    @singer= Comment.find(songid).singer

    ko = URI::encode("#{@title}  #{@singer}")
    page = Nokogiri::HTML(open('http://search.bugs.co.kr/track?q='+ ko).read , nil, 'utf-8')


    if page.css('a.trackInfo')[0] != nil
      @nokogiri = page.css('a.trackInfo')[0]['href']

      new_page = Nokogiri::HTML(open("#{@nokogiri}").read , nil, 'utf-8')

      @lylic = new_page.css('div.lyricsContainer').css('p').to_s.html_safe
      @thumnail = new_page.css('img')[0]['src']

    else
      @nokogiri = "검색 결과 없음"
    end
  end
  
  def rating
     rating = params[:rating]
     postid = params[:post_id]
     userid = params[:user_id]

     jumsoo = Dfficulty.new(score: rating, user_id: userid , post_id: postid )
     jumsoo.save
  end
end

app/controllers/star_controller.rb
class StarController < ApplicationController
  def rating
     rating = params[:rating].to_i
     postid = params[:id].to_i
     isnil = Difficulty.where(user_id: current_user.id, post_id: postid)
     if isnil.empty?
       add_score = Difficulty.new(score: rating, user_id: current_user.id, post_id: postid )
       add_score.save
       @jumsoo = add_score.score
     else
       @jumsoo = isnil.take.score
     end
     
     sum = Post.find(postid).difficulties.pluck(:score).sum
     count = Post.find(postid).difficulties.pluck(:score).count
     @avg = sum/count
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/star_helper.rb
module StarHelper
end

app/views/home/_comment_correct_input.html.erb
<%= form_tag(home_correct_comment_process_path(c_id), method: "POST", remote: true) do %>
  <%= text_field_tag 'title', c_title, class: 'materialize-text' %>
  <%= text_field_tag 'singer', c_singer, class: 'materialize-text' %>
  <%= text_area_tag 'content', c_content, class: 'materialize-textarea' %>
  <%= button_tag 'Submit', class: 'btn waves-effect waves-light' %>
<% end %>

app/views/home/_comment_list.html.erb
<% show.comments.reverse.each do |c| %>
  <div id="comment_<%= c.id %>">
    <%= link_to "#{c.title} : #{c.singer}", home_nokogiri_path(song_id: c.id), id: "nokogiri_#{c.id}", remote: true %><br>
    <%= c.content %><br>
    <%= c.writer %><br>
    <%= c.created_at.in_time_zone("Asia/Seoul").strftime("%Y년%m월%d일 %H시%M분") %>
    <% if current_user.email == c.writer %>
      <%= link_to "수정", home_correct_comment_path(c.id), class: "green-text text-accent-3", remote: true %>
      <%= link_to "삭제", home_delete_comment_path(c.id), class: "green-text text-accent-3", remote: true %><hr>
    <% else %>
    
    <% end %>
  </div>
<% end %>

app/views/home/_like_count.html.erb
<% if Like.where(user_id: current_user.id, post_id: postid).empty? %>
  <%= link_to "좋아요 #{count}명", home_like_path(post_id: postid), id: "like_#{postid}", remote: true %>
<% else %>
  <%= link_to "좋아요 취소 #{count}명", home_like_path(post_id: postid), id: "like_#{postid}", remote: true %>
<% end %>

app/views/home/_list.html.erb
<div class="container">
  <div class="row">
    <% posts.each do |p| %>
    <div class="col s12 m6">
      <div class="card">
        <div class="card-image" style="cursor:pointer" onclick="location.href='/home/show/<%= p.id %>'">
          <% if p.genre == nil %>
            <img class="postimg" src=<%= asset_path("etc.png") %>>
          <% else %>
            <img class="postimg" src=<%= asset_path("#{p.genre}.png") %>>
          <% end %>
          <input type="hidden" id="post_id" name="post_id" value="<%= p.id %>"/>
          <span class="card-title"><%= p.genre %></span>
          <span class="card-date"><%= p.created_at.in_time_zone("Asia/Seoul").strftime("%Y년%m월%d일 %H시%M분") %></span>
        </div>
        <div class="card-content">
          <% if p.content == nil || p.content == "" %>
            <p>어떤 음악일지 맞춰보세요~!</p>
          <% else %>
            <p class="post_content"><%= p.content %></p>
          <% end %>
        </div>
        <div class="card-action">
          <!-- "home_like_path() : route.rb에 먼저 경로가 지정되어 있어야 한다. -->
          <!-- 좋아요를 이미 눌렀다면 "좋아요 취소 n명"으로 나타난다. -->
          <% if Like.where(user_id: current_user.id, post_id: p.id).empty? %>
            <%= link_to "좋아요 #{p.members.count}명", home_like_path(post_id: p.id), id: "like_#{p.id}", remote: true %>
          <% else %>
            <%= link_to "좋아요 취소 #{p.members.count}명", home_like_path(post_id: p.id), id: "like_#{p.id}", remote: true %>
          <% end %>
          <p class="card-difficulty">
          </p>
        </div>
      </div>
    </div>
    <% end %>
  </div>
</div>

app/views/home/_nokogiri.html.erb
<div class="modal-content">
  <h4><%= @title %><br><%= @singer %></h4>
  <p><%= nokogiri %></p>
  <p><image src="<%= thumnail %>"></p>
  <%= lylic %>

</div>
<div class="modal-footer">
  <a href="" class=" modal-action modal-close waves-effect waves-green btn-flat">close</a>
</div>

app/views/home/comment.js.erb
$("#comment").html(
    "<%= escape_javascript(render partial: 'home/comment_list', locals: { show: @show_one }) %>"
);
$("#title").val("");
$("#content").val("");
$("#singer").val("");

app/views/home/correct_comment.js.erb
$("#comment_<%= @c_id %>").html(
    "<%= escape_javascript(render partial: 'home/comment_correct_input', locals: { c_id: @c_id, c_title: @c_title, c_content: @c_content, c_singer: @c_singer }) %>"
);

app/views/home/correct_comment_process.js.erb
$("#comment_<%= @c_id %>").html(
    "<%= escape_javascript(render partial: 'home/comment_correct_process', locals: { id: @c_id, title: @c_title, content: @c_content, date: @c_date }) %>"
);

app/views/home/index.html.erb
<div class="container" style="margin-top:30px;">  
  <div class="row">
    <form method="POST" action="/home/post" enctype="multipart/form-data">
      <select id="genre" class="browser-default" name="genre">
        <option value="" disabled selected>장르를 고르세요</option>
        <option value="etc">기타</option>
        <option value="newage">뉴에이지</option>
        <option value="rock">락&롤</option>
        <option value="reggae">레게</option>
        <option value="ballad">발라드</option>
        <option value="RnB">R&B</option>
        <option value="jazz">재즈</option>
        <option value="classic">클래식</option>
        <option value="hiphop">힙합</option>
      </select>
      <div class="row">
        <div class="input-field col s12">
          <textarea id="textarea" class="materialize-textarea" name="content"></textarea>
          <label for="textarea">궁금한 곡에 대한 추가 설명을 적어주세요.</label>
        </div>
        <div class="input-field col s12">
          <input type="file" id="fileupload" class="materialize-textarea" name="file" onchange="changemanual2();">
        </div>
      </div>
      <button id="submit_btn" class="btn waves-effect waves-light" type="submit" name="action">Submit</button>
    </form>
  </div>
  <table id="recordingslist">
    <tr>
    <td class="btn_td"><button id="startbtn" class="record-button" onclick="startRecording(this);">record</button></td>
    <td class="btn_td"><button id="stopbtn" class="record-button" onclick="stopRecording(this);" disabled="disabled">stop</button></td>
    <td class="audio_td"><audio id="audio" src="" controls=true style="margin:0px;"></audio></td>
    <td class="manual_td"><p id="manual">녹을을 시작해주세요. (녹음 기능은 Chrome에서만 가능합니다.)</p></td>
    </tr>
    <tr>
      <td colspan=4 id="downloadlink"></td>
    </tr>
  </table>
  <pre id="log"></pre>
</div>
<%= render :partial => "list", locals: {posts: @posts} %>

<script>
// ajax file upload 부분
var audio_context;
var recorder;

// audio record 부분

function startUserMedia(stream) {
  var input = audio_context.createMediaStreamSource(stream);  // create MediaStreamAudioSourceNode object
  console.log('Media stream created.');

  recorder = new Recorder(input);
  console.log('Recorder initialised.');
}

function startRecording(button) {
  recorder && recorder.record();
  button.disabled = true;
  $("#stopbtn").removeAttr("disabled");
  $("#manual").html("stop 버튼을 눌러주세요");
  console.log('Recording...');
}

function stopRecording(button) {
  recorder && recorder.stop();
  button.disabled = true;
  // 한 번 녹음 후에 다시 녹음되지 않도록 설정
  // button.previousElementSibling.disabled = false;
  $("#manual").html("해당 파일을 다운받아 주세요");
  console.log('Stopped recording.');

  // create WAV download link using audio data blob
  createDownloadLink();
  
  recorder.clear();
}

function createDownloadLink() {
  recorder && recorder.exportWAV(function(blob) {
    var url = URL.createObjectURL(blob);
    // var li = document.createElement('li');
    var au = document.getElementById('audio');
    var hf = document.createElement('a');
    hf.setAttribute("id", "uploads");
    hf.setAttribute("onclick", "changemanual();")

    // au.controls = true;
    au.src = url;
    hf.href = url;
    hf.download = new Date().toISOString() + '.wav';  // toISOString() : ISO format의 시간 반환
    hf.innerHTML = hf.download;
    // li.appendChild(au);
    // li.appendChild(hf);
    downloadlink.appendChild(hf);
  });
}

function changemanual() {
  $("#manual").html("다운 받은 파일을 선택해 주세요");
}

function changemanual2() {
  $("#manual").html("Submit 버튼을 눌러 완료해 주세요");
}

$(document).ready(function() {
  try {
    // webkit shim
    window.AudioContext = window.AudioContext || window.webkitAudioContext;
    navigator.getUserMedia = navigator.getUserMedia || navigator.webkitGetUserMedia;
    window.URL = window.URL || window.webkitURL;

    audio_context = new AudioContext;
    console.log('Audio context set up.');
    console.log('navigator.getUserMedia ' + (navigator.getUserMedia ? 'available.' : 'not present!'));
  } catch (e) {
    alert('No web audio support in this browser!');
  }
  
  // navigator.getUserMedia : 사용자의 video, audio 기능 허용 관련
  // navigator.getUserMedia(constraints, successCallback, errorCallback);
  // 성공일 경우, startUserMedia 함수 실행
  navigator.getUserMedia({audio: true}, startUserMedia, function(e) {
    console.log('No live audio input: ' + e);
  });
});

</script>

app/views/home/like.js.erb
$("#like_" + <%= @post_id %>).html(
    "<%= escape_javascript(render partial: 'home/like_count', locals: { count: @count, postid: @post_id }) %>"
);

app/views/home/list.html.erb
<div class="container">
    <div class="row">
        <% @posts.each do |p| %>
        <div class="col s12 m6">
            <div class="card">
                <div class="card-image">
                    <img src=<%= asset_path("hiphop.png") %>>
                    <span class="card-title"><%= p.genre %></span>
                </div>
                <div class="card-content">
                    <p><%= p.content %></p>
                </div>
                <div class="card-action">
                    <a href="#">This is a link</a>
                </div>
            </div>
        </div>
        <% end %>
    </div>
</div>

app/views/home/nokogiri.js.erb
$("#modal").html(
  "<%= escape_javascript(render partial: 'home/nokogiri', locals: { nokogiri: @nokogiri, lylic: @lylic, thumnail: @thumnail }) %>"
);

$(document).ready(function(){
  $("#modal").openModal();
});

app/views/home/show.html.erb
<div class="container">
  <div class="row">
    <div class="col s12 m6">
      <% @show.each do |s| %>
      <div class="card">
        <div class="card-image">
          <img src=<%= asset_path("#{s.genre}.png") %>>
          <span class="card-title"><%= s.genre %></span>
          <span class="card-date"><%= s.created_at.in_time_zone("Asia/Seoul").strftime("%Y년%m월%d일 %H시%M분") %></span>
        </div>
        <div class="card-content">
          <audio controls source src="<%= s.file_name %>" type="audio/wav"></audio>
        </div>
        <div class="card-content">
          <%= simple_format(s.content) %>
        </div>
        <div class="card-action">
          <p class="card-difficulty"><span id="score">난이도는?</span><%= render partial: 'star/rating', locals: { s: s}  %><span</p>
          <!-- "home_like_path() : route.rb에 먼저 경로가 지정되어 있어야 한다. -->
          <!-- 좋아요를 이미 눌렀다면 "좋아요 취소 n명"으로 나타난다. -->
          <% if Like.where(user_id: current_user.id, post_id: s.id).empty? %>
            <%= link_to "좋아요 #{@count}명", home_like_path(post_id: s.id), id: "like_#{s.id}", remote: true %>
          <% else %>
            <%= link_to "좋아요 취소 #{@count}명", home_like_path(post_id: s.id), id: "like_#{s.id}", remote: true %>
          <% end %>
        </div>
        <div class="card-content">
          <%= form_tag("/home/comment", method: "POST", remote: true) do %>
            <%= hidden_field_tag 'postid', s.id %>
            <%= text_field_tag 'title', nil, class: 'materialize-text', placeholder: '곡 제목' %>
            <%= text_field_tag 'singer', nil, class: 'materialize-text', placeholder: '가수명' %>
            <%= text_area_tag 'content', nil,  class: 'materialize-textarea', placeholder: '자세한 설명을 적어주세요.' %>
            <%= button_tag 'Submit', class: 'btn waves-effect waves-light' %>
            <% if current_user.id == s.user.id %>
              <%= button_tag 'Correct', type: 'button', class:'btn waves-effect waves-light amber accent-4', onclick: "location.href = '/home/correct/#{s.id}'" %>
              <%= button_tag 'Delete', type: 'button', class:'btn waves-effect waves-light red', onclick: "location.href = '/home/delete/#{s.id}'" %>
            <% else %>
              <%= button_tag 'Correct', type: 'button', class:'btn waves-effect waves-light amber accent-4', onclick: "location.href = '/home/correct/#{s.id}'", disabled: true %>
              <%= button_tag 'Delete', type: 'button', class:'btn waves-effect waves-light red', onclick: "location.href = '/home/delete/#{s.id}'", disabled: true %>
            <% end %>
          <% end %>
        </div>
        <div id="comment" class="card-content">
          <% s.comments.reverse.each do |c| %>
            <div id="comment_<%= c.id %>">
              <%= link_to "#{c.title}", home_nokogiri_path(song_id: c.id), id: "nokogiri_#{c.id}", remote: true %><br>
              <%= c.content %><br>
              <%= c.writer %><br>
              <%= c.created_at.in_time_zone("Asia/Seoul").strftime("%Y년%m월%d일 %H시%M분") %>
              <% if current_user.email == c.writer %>
                <%= link_to "수정", home_correct_comment_path(c.id), class: "green-text text-accent-3", remote: true %>
                <%= link_to "삭제", home_delete_comment_path(c.id), class: "green-text text-accent-3", remote: true %><hr>
              <% else %>
                
              <% end %>
            </div>
          <% end %>
        </div>
        <div id="modal" class="modal"></div>
      </div>
      <% end %>
    </div>
  </div>
</div>

app/views/home/show.js.erb
$("#comment").html(
    "<%= escape_javascript(render partial: 'home/comment_list', locals: { show: @show_one }) %>"
);
$("#title").val("");
$("#content").val("");

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Workspace</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <style type='text/css'>
    ul { list-style: none; }
    #recordingslist audio { display: block; margin-bottom: 10px; }
  </style>
  <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
</head>
<body>
  <nav>
      <div class="nav-wrapper">
        <a href="/" class="brand-logo">허밍허밍베이비</a>
        <% if user_signed_in? %>
            <p class="whoislogin"><%= current_user.email %></p>
            <ul id="nav-mobile" class="right hide-on-med-and-down">
                <li><a href="/users/sign_out">로그아웃</a></li>
            </ul>
        <% else %>
            <ul id="nav-mobile" class="right hide-on-med-and-down">
              <li><a href="sass.html">로그인</a></li>
              <li><a href="badges.html">회원가입</a></li>
              <li><a href="collapsible.html">JavaScript</a></li>
            </ul>
        <% end %>
      </div>
  </nav>



  <%= yield %>

  <footer class="page-footer">
         <div class="container">
           <div class="row">
             <div class="col l6 s12">
               <h5 class="white-text">당신의 허접한 콧소리로 리얼뮤직을 찾아드립니다.</h5>
               <p class="grey-text text-lighten-4">음악은...당신에게 허용된 유일한 마약입니다... <br>
                우리의 마약을 찾아서 고고!! 고고!!
               </p>
             </div>
             <div class="col l4 offset-l2 s12">
               <h5 class="white-text">Links</h5>
               <ul>
                 <li><a class="grey-text text-lighten-3" href="#!">Link 1</a></li>
                 <li><a class="grey-text text-lighten-3" href="#!">Link 2</a></li>
                 <li><a class="grey-text text-lighten-3" href="#!">Link 3</a></li>
                 <li><a class="grey-text text-lighten-3" href="#!">Link 4</a></li>
               </ul>
             </div>
           </div>
         </div>
         <div class="footer-copyright">
           <div class="container">
           © 2016 Copyright SNULikeLion Team1
           <a class="grey-text text-lighten-4 right" href="#!">More Links</a>
           </div>
         </div>
   </footer>


</body>
</html>

app/views/star/_rating.erb
<%= form_tag(star_rating_path(s.id), method: "POST", remote: true) do %>
  <div class="input-field col s12">
    <p class="range-field">
    <input type="range" id="test5" min="0" max="10" name="rating" />
    </p>
  </div>
  <%= button_tag 'Submit', class: 'btn waves-effect waves-light' %>
<% end %>

app/views/star/rating.js.erb
$("#score").html(
<%= @avg %>
);